apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: front-end
    Name: Server
spec:
  restartPolicy: Never
  containers:
  - name: succeed
    image: ubuntu:latest
    command: ['sh', '-c', 'echo "Hello World!" && sleep 20']