apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  labels:
    app: myservic
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30009    
  selector:
    name: myapp