apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: rkn
    image: rknktm/secret
    ports:
      - containerPort: 80
    env:
      - name: user
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: username
      - name: pass
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: password
  restartPolicy: Never
      
