apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: rkn
    image: rknktm/secret2
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: mysecret2