apiVersion: v1
   
kind: Pod
   
metadata:
   
  name: env-single-secret
  labels:
    test: dev
   
spec:
   
  containers:
   
  - name: env-con
   
    image: rknktm/secret
   
    env:
   
      - name: user
    
        valueFrom:
    
          secretKeyRef:
    
            name: mysecret
    
            key: user
      - name: pass
    
        valueFrom:
    
          secretKeyRef:
    
            name: mysecret
    
            key: pass